### ISSUE TITLE
Error starting app version 0.5.2 from testing repo

### ISSUE THREAD

**Issue by Havege** [flathub/com.github.cfcurtis.pdfstitcher#2]
When i run "flatpak run com.github.cfcurtis.pdfstitcher" im getting this error:
python3: can't open file '/app/pdfstitcher/pdfstitcher-0.5.2/pdfstitcher.py': [Errno 2] No such file or directory

Solved by moving \_\_main\_\_.py to parent directory and editing launch script to call \_\_main\_\_.py instead of pdfstitcher.py directly

**Comment by cfcurtis** [comment]
Apologies, I just saw this. This error was a result of reorganizing code to get things working better with pypi, so I am reluctant to move files around upstream. At some point I would like to incorporate updating the flatpak build with the pdfstitcher release workflow, as I realize flatpak is lagging at the moment.
